
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${PORT}"
    restart: always
    networks:
      - my-network
    env_file:
      - .env  # 👈 Đọc các biến từ file .env ở thư mục gốc
    extra_hosts:
      - "host.docker.internal:${HOST_IP}" # 👈 giúp gọi Flask qua alias

  frontend:
    build: ./frontend
    ports:
      - "3003:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:${HOST_IP}" # 👈 chỉ cần nếu frontend gọi Flask

networks:
  my-network:
    driver: bridge

